- name: Playbook
  hosts: all
  become: yes
  become_user: root
  tasks:
    - name: Print OS version
      shell: cat /etc/centos-release && echo "Kernel:\ $(uname -r)"
      register: printOSVersion

    - debug: msg="{{ printOSVersion.stdout }}"

    - name: Disable SELinux
      selinux: state=disabled

    - name: Update system
      dnf:
        name: "*"
        state: latest

    - name: Install epel-release
      dnf:
        name: epel-release
        state: latest

    - name: Install essential packages
      dnf:
        name: gcc,make,perl,kernel-devel,kernel-headers,bzip2,dkms,nano,zip,wget,git
        state: latest

    - name: Install ZSH
      dnf:
        name: zsh,util-linux-user
        state: latest

    - name: Change default shell
      shell: chsh -s $(which zsh) vagrant

    - name: Install oh-my-zsh and custom plugins
      shell: |
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
        rm -rf ${ZSH_CUSTOM:-/home/vagrant/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
        rm -rf ${ZSH_CUSTOM:-/home/vagrant/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

        git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-/home/vagrant/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
        git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-/home/vagrant/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting

    #- name: Copy zsh.rc
    #  shell: cp provisioning/zshrc.zsh-template /home/vagrant/.zshrc